def modify_prompt(session_params: dict, teacher_profile: dict) -> str:
    """
    Construye el prompt para la IA a partir de los parámetros
    de la sesión y el perfil del docente.
    """
    return (
        f"Eres un experto en planificación curricular del sistema educativo peruano. "
        f"Genera una sesión de aprendizaje completa con los siguientes datos:\n\n"
        f"DATOS DEL DOCENTE:\n"
        f"- Institución Educativa: {teacher_profile['institucion_educativa']}\n"
        f"- Docente: {teacher_profile['nombre_docente']}\n"
        f"- Área: {teacher_profile['area']}\n"
        f"- Especialidad: {teacher_profile['especialidad']}\n"
        f"- Ciclo: {teacher_profile['ciclo']}\n"
        f"- Tipo de Rúbrica: {teacher_profile['tipo_rubrica']}\n\n"
        f"DATOS DE LA SESIÓN:\n"
        f"- Título: {session_params['titulo']}\n"
        f"- Grado y Sección: {session_params['grado_seccion']}\n"
        f"- Número de Sesión: {session_params['numero_sesion']}\n"
        f"- Nombre del Módulo: {session_params['nombre_modulo']}\n"
        f"- Nombre de la Unidad: {session_params['nombre_unidad']}\n"
        f"- Duración Total: {session_params['duracion']}\n"
        f"- Materiales y Recursos: {session_params['materiales_recursos']}\n\n"
        f"Responde ÚNICAMENTE en el siguiente formato exacto, sin markdown, "
        f"sin asteriscos, sin numerales, sin encabezados adicionales. "
        f"Cada clave en una línea con el formato 'clave: contenido':\n\n"
        f"proposito: ...\n"
        f"indicador_logro: ...\n"
        f"desempeno: ...\n"
        f"campo_tematico: ...\n"
        f"evidencia_proceso: ...\n"
        f"evidencia_producto_final: ...\n"
        f"evidencia_actuacion: ...\n"
        f"criterio_desempeno: ...\n"
        f"instrumento: ...\n"
        f"proposito_aprendizaje: ...\n"
        f"introduccion: ...\n"
        f"desarrollo_contenidos: ...\n"
        f"desarrollo_actividades: ...\n"
        f"evaluacion_formativa: ...\n"
        f"retroalimentacion: ...\n"
        f"cierre: ...\n"
        f"extension: ...\n"
        f"rubrica: ...\n"
    )
